<header >
  <?php if (!isset($_SESSION["email"])): ?>
    <div class="bg-img">
      <br><br>
      <div class="col-6 mx-auto">
          <h1 class="header-h1">Cooking gone wrong?</h1><br>
          <h1 class="header-h1">Late night at office?</h1><br>
          <h1 class="header-h1">Assginment due midnight?<h1> <br>
          <h1 class="header-h1">Hungry?<h1><br>
          <p class= "header-p" style="text-align: center;">Order food from favourite restaurants near you</p><br><br>
          <p class= "header-p" style="text-align: center;">Just Login!</p>
          <!-- <a style="font-size: 0.5em;" href="https://www.freepik.com/free-photos-vectors/background">Background photo created by freepik - www.freepik.com</a> -->
      </div>
      <br>
      
    </div>
  <?php endif ?>
</header>
<?php if (isset($_SESSION["email"])): ?>
  <div class="bg-img">
  <br>
    <main class="container home">
      <br>
        <?php echo "<h5 class='white-text'>Hi ".$_SESSION['name']."!  </h5><br>"; ?>
        <!-- change the action -->
        <form action="<?php echo base_url();?>" method="GET" style="margin-bottom: 3rem;">
            <!-- <label class="shift-right card-text">Look for the food near you:</label> -->
            <input type="text" class="search-style" placeholder="Look for the food near you" name="zomquery">
            <input type="submit" class="btn bg-four btn-search" name="zomsubmit" value="Search">
        </form>
        <?php
          if (isset($_GET['zomsubmit'])) {
            $zomquery = $_GET['zomquery'];
            # Continue running code api 4ad151728c99a2d47f8ed5a0bb4ba1cb
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, "https://developers.zomato.com/api/v2.1/search?q=".$zomquery."&start=0&count=10");
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
            $headers = array(
              "Accept: application/json",
              "User-Key: f0baf53bd8c31d3c625e9d9c0d379379"
              );
              
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close ($ch);

            $zomdata = json_decode($result);
            $zomrestaurants = $zomdata->restaurants;

          //echo "<pre>"; print_r($zomrestaurants); echo "</pre>";

            if (count($zomrestaurants) == 0) {
              echo '<b style="margin-bottom: 3rem;">No results found! Try searching like burger, pizza, shushi etc.</b>'; 
              //exit();
            }

            echo '<div class="container">';
            echo '<div class="row">';
            foreach ($zomrestaurants as $restaurant) {

              echo '<div class="col-sm" style="margin-bottom: 3rem;">';
              echo '<div class="col-sm-6">';
              echo '<div class="card text-center" style="width: 18rem; height:36rem; box-shadow: 2px 2px #d3d3d3;">';
              echo '<div class="card-header bg-four text-black">'.@$restaurant->restaurant->name.'</div><br>';
              if ($restaurant->restaurant->thumb != "") {
                echo '<img class="card-img-top" width="330" src="'.@$restaurant->restaurant->thumb.'" alt="Image not available" /><br/>';
              }else 
              {
                echo '<img class="card-img-top" width="330" src="" alt="Image not available"/><br/>';
              }
              echo '<div class="card-body">';
              echo '<h6 class="card-title">User rating: '.@$restaurant->restaurant->user_rating->rating_text.'( '.@$restaurant->restaurant->user_rating->aggregate_rating.'/5 ) <br>Total votes: '.@$restaurant->restaurant->user_rating->votes.'</h6>';
              echo '<p class="card-text">Address:'.@$restaurant->restaurant->location->address.'.</p>';
              echo '</div>';
              echo '<div class="card-footer bg-transparent bg-primary text-black">';
              echo '<a href="'.@$restaurant->restaurant->url.'" class="btn bg-link">Visit Resturant</a>';
              echo '</div>';
              echo '</div>';
              echo '</div>';
              echo '</div>';
              echo '<br><br>';

            }
            echo '</div>';
            echo '</div>';
          }
          else {
            
            //exit();
          }
        ?>
        <br>
    </main>
  </div>
<?php endif ?>